/* Modifica únicamente este archivo para añadir categorías, subcategorías y productos. */
window.catalogData = {
  siteConfig: {
    facebookUrl: "https://www.facebook.com/segundavidastores"
  },
  categories: [
    { name: "Ropa", subcategories: ["Mujer", "Hombre", "Niños", "Niñas", "Lluvia"] },
    { name: "Hogar", subcategories: ["Muebles", "Decoración", "Cocina", "Otros"] },
    { name: "Calzado", subcategories: ["Niñas", "Botas", "Escolares", "Casual", "Niños"]}
  ],
  products: [
    { id: 1, name: "Vestido suéter tejido gris - Talla S", brand: "Style & Co.", category: "Ropa", subcategory: "Mujer", price: 500, description: "Vestido tejido de manga corta, con franjas horizontales y detalles brillantes.", condition: "Muy buena", facebookUrl: "https://www.facebook.com/share/p/17cY7txNNU/", images: ["images/products/1/vestido.webp", "images/products/1/IMG_9571.webp", "images/products/1/IMG_9572.webp", "images/products/1/IMG_9573.webp", "images/products/1/IMG_9574.webp", "images/products/1/IMG_9575.webp", "images/products/1/IMG_9576.webp"], available: true },
    { id: 2, name: "Blusa para mujer ByDesign geométrica con diseño de cuello de redondo cerrado - Talla M", brand: "ByDesign", category: "Ropa", subcategory: "Mujer", price: 350, description: "Blusa de dama marca BYdesign, con diseño geométrico en tonos negro, blanco y beige, con detalles de contraste que le dan un estilo moderno y versátil. composición 95% poliéster / 5% spandex, Ideal para uso casual, oficina, viajes o una ocasión especial, Estampado Geometrico", condition: "Excelente", facebookUrl: "#", images: ["images/products/2/blusa2.webp","images/products/2/IMG_9577.webp","images/products/2/IMG_9578.webp","images/products/2/IMG_9579.webp","images/products/2/IMG_9580.webp","images/products/2/IMG_9581.webp","images/products/2/IMG_9582.webp","images/products/2/IMG_9584.webp","images/products/2/IMG_9585.webp","images/products/2/IMG_9586.webp","images/products/2/IMG_9587.webp"], available: true },
    { id: 3, name: "Chaleco Y2K Mossimo Vintage Piel Blanco Sin Mangas Corbata Frontal Para Mujer - Talla XL", brand: "Mossimo Supply Co.", category: "Ropa", subcategory: "Mujer", price: 600, description: "Chaleco vintage para dama marca Mossimo Supply Co., elaborado en piel sintética tipo faux fur de pelo largo en color blanco/ivory. Su diseño sin mangas y frente abierto lo hace una prenda versátil para complementar outfits casuales, boho o estilo Y2K / vintage.", condition: "Excelente", facebookUrl: "#", images: ["images/products/3/chaleco_3.webp", "images/products/3/IMG_9597.webp", "images/products/3/IMG_9589.webp", "images/products/3/IMG_9590.webp", "images/products/3/IMG_9591.webp", "images/products/3/IMG_9592.webp", "images/products/3/IMG_9593.webp", "images/products/3/IMG_9594.webp", "images/products/3/IMG_9595.webp", "images/products/3/IMG_9596.webp"], available: true },
    { id: 4, name: "Chamarra / Saco Militar Black – August Silk Sportswear - Talla L", brand: "August Silk", category: "Ropa", subcategory: "Mujer", price: 450, description: "¡Dale un toque único y sofisticado a tu outfit con esta espectacular prenda de estilo militar!Esta chamarra de la prestigiada marca August Silk combina a la perfección la formalidad de un saco con la comodidad de un suéter de alta gama. Su diseño de doble botonadura decorativa dorada evoca la tendencia Y2K y militar clásico, convirtiéndola en una pieza atemporal y sumamente versátil.", condition: "Buena", facebookUrl: "#", images: ["images/products/4/chamarra_1.webp", "images/products/4/chamarra_2.webp", "images/products/4/IMG_9569.webp", "images/products/4/IMG_9570.webp"], available: true },
    { id: 5, name: "Blazer Negro Clásico George – ¡Un básico infaltable! - Talla 36", brand: "George Plus", category: "Ropa", subcategory: "Mujer", price: 300, description: "blazer negro de la marca George, perfecto para la oficina, eventos formales o para elevar un look casual con jeans. Tiene un corte estructurado muy favorecedor, solapas tradicionales y cierre frontal de tres botones. Incluye bolsillos decorativos con solapa al frente.", condition: "Buena", facebookUrl: "#", images: ["images/products/5/blazer_1.webp", "images/products/5/IMG_9560.webp","images/products/5/IMG_9558.webp"], available: true },
    { id: 6, name: "Sudadera Michael Kors Cremallera Completa Beige  Elastizada Terciopelo Mujer Talla Pequeña XS", brand: "Michael Kors", category: "Ropa", subcategory: "Mujer", price: 400, description: "¡Dale un toque de lujo y comodidad a tu estilo diario con esta espectacular chamarra Michael Kors original! Diseñada en una tela de terciopelo/velour ultra suave al tacto, es la prenda perfecta para armar un look casual, aesthetic o deportivo con un aire premium de los años 2000", condition: "Excelente", facebookUrl: "#", images: ["images/products/6/chamarra_1.webp", "images/products/6/IMG_9564.webp", "images/products/6/IMG_9565.webp", "images/products/6/IMG_9567.webp"], available: true },
    /*{ id: 7, name: "Botas de lluvia para niña Unicornio, material de goma impermeables con asa fáciles de poner - Talla 16", brand: "Lluvia", category: "Calzado", subcategory: "Niñas", price:250, description: "estas botas de lluvia para niños están diseñadas para mantener los pies secos y limpios en los charcos más sucios. Interior de algodón para máxima comodidad y calidez. Suela de goma duradera perfecta para explorar, saltar y jugar todo el día. Nuestro diseño de suela hace que caminar sea más fácil para los niños pequeños.", condition: "Buena", facebookUrl: "#", images: ["images/products/7/unicornio.webp","images/products/7/IMG_9600.webp","images/products/7/IMG_9601.webp","images/products/7/IMG_9602.webp","images/products/7/IMG_9603.webp","images/products/7/IMG_9604.webp","images/products/7/IMG_9605.webp"], available: true },
    { id: 8, name: "Sandalia Igor Tiras Con Velcro Azul Para Niña/Niño - Talla 16 cm", brand: "Igor", category: "Calzado", subcategory: "Niños", price: 250, description: "Las sandalias IGOR Star Tr Azul son ideales para los días de calor. Su diseño cómodo con tiras ajustables de velcro permite un ajuste seguro y práctico para que los pequeños puedan ponerse y quitarse el calzado fácilmente.", condition: "Buena", facebookUrl: "#", images: ["images/products/8/igor.webp","images/products/8/IMG_9606.webp","images/products/8/IMG_9607.webp","images/products/8/IMG_9608.webp","images/products/8/IMG_9609.webp","images/products/8/IMG_9610.webp"], available: true },
    { id: 9, name: "Sandalia Igor Unicornio Con Velcro, plástico translúcido con glitter Para Niña - Talla 14 cm", brand: "Igor", category: "Calzado", subcategory: "Niñas", price: 300, description: "Calzado infantil para la playa o piscina, las llamadas sandalias de río, sandalias de agua o sandalias cangrejeras para niña. Llevan las plantillas interiores acolchaditos y atan con velcros.", condition: "Buena", facebookUrl: "#", images: ["images/products/9/igor14.webp","images/products/9/IMG_9611.webp","images/products/9/IMG_9612.webp","images/products/9/IMG_9613.webp","images/products/9/IMG_9614.webp","images/products/9/IMG_9615.webp","images/products/9/IMG_9616.webp"], available: true },
    { id: 10, name: "Skechers Microspec Plus - Swirl Sweet Sneaker Zapatillas para Niñas - Talla 16", brand: "Skechers", category: "Calzado", subcategory: "Niñas", price: 380, description: "El estilo colorido y la comodidad se unen en las Skechers Microspec Max - Epic Brights. Este diseño ligero cuenta con una parte superior de malla y material sintético, cordones elásticos, una tira ajustable en el empeine y una mediasuela con cámara de aire visible Skech-Air®.", condition: "Excelente", facebookUrl: "#", images: ["images/products/10/sketchers10.webp","images/products/10/IMG_9646.webp","images/products/10/IMG_9647.webp","images/products/10/IMG_9648.webp","images/products/10/IMG_9649.webp","images/products/10/IMG_9650.webp","images/products/10/IMG_9651.webp"], available: true },
    { id: 11, name: "Zapatos Escolares Estilo Mary Jane Color Marino - Talla 17.5", brand: "Españoleta", category: "Calzado", subcategory: "Niñas", price: 599, description: "Suela de goma suave. Listos para que brinquen en una nube. Sujeción y confort.", condition: "Nuevos", facebookUrl: "#", images: ["images/products/11/espanoletas.webp","images/products/11/IMG_9624.webp","images/products/11/IMG_9625.webp","images/products/11/IMG_9626.webp","images/products/11/IMG_9627.webp","images/products/11/IMG_9628.webp","images/products/11/IMG_9629.webp"], available: true },
    { id: 12, name: "Zapato Victoria Azul De Lona - Talla 14.5", brand: "Victoria", category: "Calzado", subcategory: "Niñas", price: 160, description: "Zapato para niña en color azul marino, este modelo de la marca Victoria lleva un elástico en la zona del empeine y un estampado con estrellas. ", condition: "Desgastado", facebookUrl: "#", images: ["images/products/12/victoria12.webp","images/products/12/IMG_9617.webp","images/products/12/IMG_9618.webp","images/products/12/IMG_9619.webp","images/products/12/IMG_9620.webp","images/products/12/IMG_9621.webp"], available: true },
    { id: 13, name: "Playera estampada", brand: "Adidas", category: "Ropa", subcategory: "Hombre", price: 140, description: "Playera de algodón con estampado discreto, talla mediana.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 14, name: "Bolso cruzado negro", brand: "Cloe", category: "Ropa", subcategory: "Mujer", price: 290, description: "Bolso compacto con correa ajustable y cierre completo.", condition: "Muy buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 15, name: "Chamarra acolchada", brand: "Uniqlo", category: "Ropa", subcategory: "Hombre", price: 480, description: "Chamarra ligera acolchada para clima fresco, talla grande.", condition: "Excelente", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 16, name: "Silla plegable metálica", brand: "Tramontina", category: "Hogar", subcategory: "Muebles", price: 250, description: "Silla plegable resistente para interior o exterior.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 17, name: "Licuadora compacta", brand: "Oster", category: "Hogar", subcategory: "Cocina", price: 430, description: "Licuadora compacta con vaso de vidrio y dos velocidades.", condition: "Muy buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 18, name: "Sudadera con capucha", brand: "Puma", category: "Ropa", subcategory: "Niños", price: 180, description: "Sudadera suave con capucha, talla 10 años.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 19, name: "Espejo redondo", brand: "Home Collection", category: "Hogar", subcategory: "Decoración", price: 310, description: "Espejo redondo con borde dorado para recibidor o recámara.", condition: "Excelente", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 20, name: "Caja organizadora con tapa", brand: "Sterilite", category: "Hogar", subcategory: "Otros", price: 110, description: "Caja plástica transparente para almacenar ropa o accesorios.", condition: "Muy buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: true },
    { id: 21, name: "Juego de tazas de cerámica", brand: "Corona", category: "Hogar", subcategory: "Cocina", price: 180, description: "Juego de cuatro tazas de cerámica sin grietas ni despostilladuras.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false },
    { id: 22, name: "Pantalón de mezclilla recto", brand: "American Eagle", category: "Ropa", subcategory: "Mujer", price: 260, description: "Pantalón de mezclilla de tiro medio, talla 28.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false },
    { id: 23, name: "Zapatos de vestir café", brand: "Flexi", category: "Ropa", subcategory: "Hombre", price: 340, description: "Zapatos de piel para vestir, talla 27.", condition: "Muy buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false },
    { id: 24, name: "Mesa de centro", brand: "Muebles Dico", category: "Hogar", subcategory: "Muebles", price: 900, description: "Mesa de centro rectangular con acabado color nogal.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false },
    { id: 25, name: "Cojín decorativo mostaza", brand: "H&M Home", category: "Hogar", subcategory: "Decoración", price: 130, description: "Cojín decorativo de textura suave, 45 por 45 cm.", condition: "Excelente", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false },
    { id: 26, name: "Playera deportiva", brand: "Reebok", category: "Ropa", subcategory: "Mujer", price: 150, description: "Playera deportiva de secado rápido, talla mediana.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false },
    { id: 27, name: "Mochila escolar", brand: "Jansport", category: "Ropa", subcategory: "Niños", price: 200, description: "Mochila escolar con dos compartimentos principales.", condition: "Muy buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false },
    { id: 28, name: "Hervidor eléctrico", brand: "Hamilton Beach", category: "Hogar", subcategory: "Cocina", price: 270, description: "Hervidor eléctrico de acero inoxidable, capacidad de un litro.", condition: "Buena", facebookUrl: "#", images: ["images/products/placeholder.svg"], available: false }*/
  ]
};